[package]
authors = ["Dragan Rakita <dragan0rakita@gmail.com>"]
description = "revm primitives"
edition = "2021"
keywords = ["no_std", "ethereum", "evm", "revm", "types"]
license = "MIT"
name = "revm-primitives"
repository = "https://github.com/bluealloy/revm"
version = "9.0.1"
readme = "../../README.md"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints.rust]
unreachable_pub = "warn"
unused_must_use = "deny"
rust_2018_idioms = "deny"

[lints.rustdoc]
all = "warn"

[dependencies]
alloy-primitives = { version = "0.8.2", default-features = false, features = [
    "rlp",
] }
hashbrown = "0.14"

# utils
cfg-if = { version = "1.0", default-features = false }

[build-dependencies]
hex = { version = "0.4", default-features = false }

[features]
default = ["std"]
std = ["alloy-primitives/std", "hex/std"]
hashbrown = []
serde = ["alloy-primitives/serde", "hex/serde", "hashbrown/serde"]
arbitrary = ["std", "alloy-primitives/arbitrary"]
asm-keccak = ["alloy-primitives/asm-keccak"]
rand = ["alloy-primitives/rand"]
