[package]
authors = ["Dragan Rakita <dragan0rakita@gmail.com>"]
edition = "2021"
name = "revme"
keywords = ["ethereum", "evm"]
license = "MIT"
repository = "https://github.com/bluealloy/revm"
description = "Rust Ethereum Virtual Machine Executable"
version = "0.10.1"

[dependencies]
# revm
revm = { workspace = true, features = [
    "std",
    "serde-json",
    "hashbrown",
    "c-kzg",
    "blst",
] }

hash-db = "0.15"
hex = "0.4"
hashbrown = "0.14"
indicatif = "0.17"
microbench = "0.5"
plain_hasher = "0.2"

alloy-rlp = { version = "0.3", default-features = false, features = [
    "arrayvec",
    "derive",
] }
alloy-sol-macro = "0.8.0"
alloy-sol-types = "0.8.2"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
clap = { version = "4", features = ["derive"] }
thiserror = "1.0"
triehash = "0.8"
walkdir = "2.5"
k256 = { version = "0.13.3", features = ["ecdsa"] }
