[package]
authors = ["Dragan Rakita <dragan0rakita@gmail.com>"]
description = "revm Interpreter"
edition = "2021"
keywords = ["no_std", "ethereum", "evm", "revm", "interpreter"]
license = "MIT"
name = "revm-interpreter"
repository = "https://github.com/bluealloy/revm"
version = "10.0.1"
readme = "../../README.md"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints.rust]
unreachable_pub = "warn"
unused_must_use = "deny"
rust_2018_idioms = "deny"

[lints.rustdoc]
all = "warn"

[dependencies]
# revm
bytecode.workspace = true
primitives.workspace = true
specification.workspace = true
wiring.workspace = true

derive-where = { version = "1.2.7", default-features = false }
paste = { version = "1.0", optional = true }
phf = { version = "0.11", default-features = false, optional = true, features = [
    "macros",
] }

# optional
serde = { version = "1.0", default-features = false, features = [
    "derive",
    "rc",
], optional = true }

[dev-dependencies]
database-interface.workspace = true
walkdir = "2.5"
serde_json = "1.0"
bincode = "1.3"

[features]
default = ["std", "parse"]
std = ["serde?/std", "primitives/std", "wiring/std"]
hashbrown = ["primitives/hashbrown"]
serde = ["dep:serde", "primitives/serde", "bytecode/serde", "wiring/serde"]
arbitrary = ["std", "primitives/arbitrary"]
parse = ["dep:paste", "dep:phf"]
memory_limit = ["wiring/memory_limit"]
